# Generated by Django 2.0.7 on 2018-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=2500)),
                ('phone', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
