# Generated by Django 2.0.7 on 2018-08-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsModel',
            new_name='Contact',
        ),
    ]
